### ISSUE TITLE
cargo-deb v3.1.0 needs MSRV 1.78.0

### ISSUE THREAD

**Issue by wilfried-huss** [kornelski/cargo-deb#175]
Version v3.1.0 fails to compile on rust 1.76.0 with:

```
error[E0277]: `?` couldn't convert the error to `std::io::Error`
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-deb-3.1.0/src/util/compress.rs:215:50
    |
213 | pub(crate) fn gzipped(mut content: &[u8]) -> io::Result<Vec<u8>> {
    |                                              ------------------- expected `std::io::Error` because of this
214 |     let mut compressed = Vec::new();
215 |     compressed.try_reserve(content.len() * 2 / 3)?;
    |                ----------------------------------^ the trait `From<TryReserveError>` is not implemented for `std::io::Error`
    |                |
    |                this can't be annotated with `?` because it has type `Result<_, TryReserveError>`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following other types implement trait `From<T>`:
              <std::io::Error as From<PersistError<F>>>
              <std::io::Error as From<xz2::stream::Error>>
              <std::io::Error as From<serde_json::Error>>
              <std::io::Error as From<PathPersistError>>
              <std::io::Error as From<tar::error::TarError>>
              <std::io::Error as From<rustix::backend::io::errno::Errno>>
              <std::io::Error as From<NulError>>
              <std::io::Error as From<IntoInnerError<W>>>
              <std::io::Error as From<ErrorKind>>
    = note: required for `Result<Vec<u8>, std::io::Error>` to implement `FromResidual<Result<Infallible, TryReserveError>>`
For more information about this error, try `rustc --explain E0277`.
error: could not compile `cargo-deb` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-deb v3.1.0`, intermediate artifacts can be found at `/tmp/cargo-installu1pBHZ`.
```

This is only available in v1.78.0:

https://doc.rust-lang.org/std/collections/struct.TryReserveError.html#impl-From%3CTryReserveError%3E-for-Error
